#!/bin/bash

check_requirements() {
  log_info "Verifying environment..."

  for cmd in node npm git; do
    if ! command -v "$cmd" &> /dev/null; then
      fatal_error "Missing required command: $cmd"
    fi
  done

  local current_node_version=$(node -v | tr -d 'v')
  local major_version="${current_node_version%%.*}"

  if [[ "$major_version" -lt "$MIN_NODE_VERSION" ]]; then
    fatal_error "Node v$MIN_NODE_VERSION+ required (found v$current_node_version)"
  fi
}

setup_directory() {
  if [[ -d "$PROJECT_DIR" ]]; then
    log_warn "Folder '$PROJECT_NAME' exists."
    echo -e -n "${YELLOW}  Overwrite? (y/N): ${RESET}"
    read -r confirm < /dev/tty
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
      echo "Aborting."
      exit 0
    fi
    rm -rf "$PROJECT_DIR"
  fi
  mkdir -p "$PROJECT_DIR"
  cd "$PROJECT_DIR"
}

initialize_project() {
  log_header "Core Initialization"
  npm init -y > /dev/null
  npm pkg set name="$PROJECT_NAME" type="module" > /dev/null
  log_info "package.json created"
}

install_dependencies() {
  log_header "Dependency Installation"
  
  start_spinner "Installing Vue Core"
  local CORE_DEPS="vue@$VUE_VERSION axios"
  if $USE_ROUTER; then CORE_DEPS="$CORE_DEPS vue-router@$ROUTER_VERSION"; fi
  if $USE_PINIA; then CORE_DEPS="$CORE_DEPS pinia@$PINIA_VERSION"; fi
  if $USE_DATE_LIB; then CORE_DEPS="$CORE_DEPS date-fns"; fi
  if $USE_NUMBER_LIB; then CORE_DEPS="$CORE_DEPS numeral"; fi

  if ! npm install $CORE_DEPS > /dev/null 2>&1; then
     stop_spinner
     fatal_error "Failed to install core dependencies."
  fi
  stop_spinner "Vue Core installed"

  start_spinner "Installing Dev Tools"
  local DEV_DEPS="vite@$VITE_VERSION @vitejs/plugin-vue"
  
  if $USE_TAILWIND; then DEV_DEPS="$DEV_DEPS tailwindcss@$TAILWIND_VERSION postcss autoprefixer"; fi
  if $USE_ESLINT; then DEV_DEPS="$DEV_DEPS eslint@$ESLINT_VERSION eslint-plugin-vue globals"; fi
  if $USE_PRETTIER; then DEV_DEPS="$DEV_DEPS prettier@$PRETTIER_VERSION"; fi
  if [[ "$USE_ESLINT" == "true" && "$USE_PRETTIER" == "true" ]]; then DEV_DEPS="$DEV_DEPS @vue/eslint-config-prettier"; fi
  
  if $IS_TS; then
    DEV_DEPS="$DEV_DEPS typescript vue-tsc @types/node @vue/tsconfig"
    if $USE_ESLINT; then DEV_DEPS="$DEV_DEPS @vue/eslint-config-typescript"; fi
  fi

  if ! npm install -D $DEV_DEPS > /dev/null 2>&1; then
      stop_spinner
      fatal_error "Failed to install dev dependencies."
  fi
  stop_spinner "Dev tools installed"
}

generate_structure() {
  log_header "Scaffolding Architecture"
  
  local dirs=(
    "src/api"
    "src/assets/images"
    "src/assets/styles"
    "src/components/base"
    "src/components/common"
    "src/components/features"
    "src/composables"
    "src/constants"
    "src/directives"
    "src/helpers"
    "src/layouts"
    "src/router/guards"
    "src/services"
    "src/stores"
    "src/types"
    "src/utils"
    "src/views"
  )

  for dir in "${dirs[@]}"; do
    mkdir -p "$dir"
  done
  
  log_success "Directory structure created"
}

setup_git() {
  log_header "Version Control"
  
  if ! git init > /dev/null; then
    log_warn "Git init failed. Skipped."
    return
  fi

  cat > .gitignore <<EOF
node_modules/
dist/
.DS_Store
.env
.env.*
!.env.example
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.idea/
.vscode/
*.tsbuildinfo
EOF

  git add .
  git commit -m "chore: initial commit (generated by create-vue-app)" > /dev/null 2>&1
  log_success "Git repository initialized."
}

update_scripts() {
  npm pkg set scripts.dev="vite" scripts.preview="vite preview" > /dev/null
  
  if $IS_TS; then
      npm pkg set scripts.build="vue-tsc --noEmit && vite build" > /dev/null
  else
      npm pkg set scripts.build="vite build" > /dev/null
  fi
  
  if $USE_ESLINT; then
      npm pkg set scripts.lint="eslint . --fix" > /dev/null
  fi
  
  if $USE_PRETTIER; then
      npm pkg set scripts.format="prettier --write ." > /dev/null
  fi
}
