#!/bin/bash

check_requirements() {
  log_info "Verifying environment..."

  for cmd in node npm git; do
    if ! command -v "$cmd" &> /dev/null; then
      fatal_error "Missing required command: $cmd"
    fi
  done

  local current_node_version=$(node -v | tr -d 'v')
  local major_version="${current_node_version%%.*}"

  if [[ "$major_version" -lt "$MIN_NODE_VERSION" ]]; then
    fatal_error "Node v$MIN_NODE_VERSION+ required (found v$current_node_version)"
  fi
}

setup_directory() {
  local target_desc="'$PROJECT_NAME'"
  local current_pwd=$(pwd)
  
  if [[ "$PROJECT_DIR" == "$current_pwd" ]]; then 
    target_desc="current directory"
  else
    target_desc="directory '$PROJECT_DIR'"
  fi

  if [[ -d "$PROJECT_DIR" && "$(ls -A "$PROJECT_DIR" 2>/dev/null)" ]]; then
    log_warn "Target $target_desc is not empty."
    echo -e -n "${YELLOW}  Continue and potentially overwrite files? (y/N): ${RESET}"
    read -r confirm < /dev/tty
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
      echo "Aborting."
      exit 0
    fi
    
    # If it's a sub-directory or custom path (not current working dir), we can safely wipe it
    if [[ "$PROJECT_DIR" != "$current_pwd" ]]; then
        rm -rf "$PROJECT_DIR"
        mkdir -p "$PROJECT_DIR"
    fi
  else
    mkdir -p "$PROJECT_DIR"
  fi
  
  cd "$PROJECT_DIR" || fatal_error "Could not access $PROJECT_DIR"
}

initialize_project() {
  log_header "Core Foundation"
  npm init -y > /dev/null
  
  # Set metadata
  npm pkg set \
    name="$PROJECT_NAME" \
    version="0.1.0" \
    description="A modern Vue.js application architected for scale." \
    type="module" \
    author="Jiss Johnson (https://jissjohnson.info)" \
    homepage="https://jissjohnson.info" \
    license="MIT" \
    engines.node=">=18.0.0" \
    keywords="vue, vite, tailwind, pinia, architect" \
    > /dev/null

  log_info "Manifest [package.json] initialized with metadata"
}

install_dependencies() {
  log_header "Dependency Harmonization"
  
  local core_msg="Standardizing Vue Core"
  if $USE_ROUTER; then core_msg="$core_msg + Navigation"; fi
  if $USE_PINIA; then core_msg="$core_msg + State"; fi
  
  start_spinner "$core_msg"
  local CORE_DEPS="vue@$VUE_VERSION axios"
  if $USE_ROUTER; then CORE_DEPS="$CORE_DEPS vue-router@$ROUTER_VERSION"; fi
  if $USE_PINIA; then CORE_DEPS="$CORE_DEPS pinia@$PINIA_VERSION"; fi
  if $USE_DATE_LIB; then CORE_DEPS="$CORE_DEPS date-fns"; fi
  if $USE_NUMBER_LIB; then CORE_DEPS="$CORE_DEPS numeral"; fi

  if ! npm install $CORE_DEPS > /dev/null 2>&1; then
     stop_spinner
     fatal_error "Failed to install core dependencies."
  fi
  stop_spinner "Vue Core Runtime integrated"

  local dev_msg="Configuring Environment"
  if $USE_TAILWIND; then dev_msg="Configuring UI Framework"; fi
  
  start_spinner "$dev_msg"
  local DEV_DEPS="vite@$VITE_VERSION @vitejs/plugin-vue"
  
  if $USE_TAILWIND; then DEV_DEPS="$DEV_DEPS tailwindcss@$TAILWIND_VERSION postcss autoprefixer"; fi
  if $USE_ESLINT; then DEV_DEPS="$DEV_DEPS eslint@$ESLINT_VERSION eslint-plugin-vue globals"; fi
  if $USE_PRETTIER; then DEV_DEPS="$DEV_DEPS prettier@$PRETTIER_VERSION"; fi
  if [[ "$USE_ESLINT" == "true" && "$USE_PRETTIER" == "true" ]]; then DEV_DEPS="$DEV_DEPS @vue/eslint-config-prettier"; fi
  
  if $IS_TS; then
    DEV_DEPS="$DEV_DEPS typescript vue-tsc @types/node @vue/tsconfig"
    if $USE_ESLINT; then DEV_DEPS="$DEV_DEPS @vue/eslint-config-typescript"; fi
  fi

  if ! npm install -D $DEV_DEPS > /dev/null 2>&1; then
      stop_spinner
      fatal_error "Failed to install dev dependencies."
  fi
  stop_spinner "Development ecosystem ready"
}

generate_structure() {
  log_header "Scaffolding Architecture"
  
  local dirs=(
    "src/api"
    "src/assets/images"
    "src/assets/styles"
    "src/components/base"
    "src/components/common"
    "src/components/features"
    "src/composables"
    "src/constants"
    "src/directives"
    "src/helpers"
    "src/layouts"
    "src/router/guards"
    "src/services"
    "src/stores"
    "src/types"
    "src/utils"
    "src/views"
  )

  for dir in "${dirs[@]}"; do
    mkdir -p "$dir"
  done
  
  log_success "Directory structure created"
}

setup_git() {
  log_header "Version Control"
  
  if ! git init > /dev/null; then
    log_warn "Git init failed. Skipped."
    return
  fi

  cp "$ARCHITECT_ROOT/resources/vue/.gitignore.template" ".gitignore"

  git add .
  git commit -m "chore: initial commit (generated by vue-architect)" > /dev/null 2>&1
  log_success "Git repository initialized."
}

update_scripts() {
  log_info "Synchronizing specialized scripts..."
  
  # Base Scripts
  npm pkg set \
    scripts.dev="vite" \
    scripts.build="vite build" \
    scripts.preview="vite preview" \
    > /dev/null
  
  # Type Checking
  if $IS_TS; then
      npm pkg set \
        scripts.type-check="vue-tsc --noEmit" \
        scripts.build="npm run type-check && vite build" \
        > /dev/null
  fi
  
  # Linting & Formatting
  if $USE_ESLINT; then
      npm pkg set \
        scripts.lint="eslint . --fix" \
        scripts.lint:check="eslint ." \
        > /dev/null
  fi
  
  if $USE_PRETTIER; then
      npm pkg set \
        scripts.format="prettier --write ." \
        scripts.format:check="prettier --check ." \
        > /dev/null
  fi

  # Composite Scripts
  if [[ "$USE_ESLINT" == "true" && "$USE_PRETTIER" == "true" ]]; then
      npm pkg set scripts.verify="npm run lint:check && npm run format:check" > /dev/null
  fi
}
